// Extracted Express routes from server.js
// Generated for NiceServer scaffold import

app.get(['/', '/index.html'], async (req, res, next) => {
app.get('/cart.html', async (req, res, next) => {
app.get('/help.html', async (req, res, next) => {
app.get(['/security.html', '/seguridad.html'], async (req, res, next) => {
app.get('/product.html', async (req, res, next) => {
app.get('/sitemap.xml', async (req, res) => {
app.get('/robots.txt', async (req, res) => {
app.get('/htaccess.txt', async (req, res) => {
app.get('/api/health', (_req, res) => {
app.get('/api/products', async (_req, res) => {
app.get('/api/products/:id', async (req, res) => {
app.post('/api/orders', async (req, res) => {
app.get('/api/site-config', async (_req, res) => {
app.get('/api/pages/:slug', async (req, res) => {
app.post('/api/panel/login', async (req, res) => {
app.post('/api/panel/logout', (req, res) => {
app.get('/api/panel/session', (req, res) => {
app.get('/api/panel/dashboard-summary', async (_req, res) => {
app.get('/api/panel/server-control', (req, res) => {
app.post('/api/panel/server/restart', (req, res) => {
app.post('/api/panel/server/update', (req, res) => {
app.get('/api/panel/uploads/health', (_req, res) => {
app.post('/api/panel/uploads/image', (req, res) => {
app.post('/api/panel/uploads/images', (req, res) => {
app.get('/api/panel/users', async (_req, res) => {
app.post('/api/panel/users', async (req, res) => {
app.put('/api/panel/users/:id', async (req, res) => {
app.delete('/api/panel/users/:id', async (req, res) => {
app.get('/api/panel/settings', async (_req, res) => {
app.put('/api/panel/settings/:id', async (req, res) => {
app.get('/api/panel/categories', async (_req, res) => {
app.post('/api/panel/categories', async (req, res) => {
app.put('/api/panel/categories/:id', async (req, res) => {
app.delete('/api/panel/categories/:id', async (req, res) => {
app.get('/api/panel/orders', async (_req, res) => {
app.get('/api/panel/orders/:id', async (req, res) => {
app.post('/api/panel/orders', async (req, res) => {
app.put('/api/panel/orders/:id', async (req, res) => {
app.delete('/api/panel/orders/:id', async (req, res) => {
app.get('/api/panel/product-images', async (_req, res) => {
app.post('/api/panel/product-images', async (req, res) => {
app.put('/api/panel/product-images/:id', async (req, res) => {
app.delete('/api/panel/product-images/:id', async (req, res) => {
app.get('/api/panel/page-images', async (_req, res) => {
app.post('/api/panel/page-images', async (req, res) => {
app.put('/api/panel/page-images/:id', async (req, res) => {
app.delete('/api/panel/page-images/:id', async (req, res) => {
app.get('/api/panel/pages', async (_req, res) => {
app.post('/api/panel/pages', async (req, res) => {
app.put('/api/panel/pages/:id', async (req, res) => {
app.delete('/api/panel/pages/:id', async (req, res) => {
app.get('/api/panel/products', async (_req, res) => {
app.post('/api/panel/products', async (req, res) => {
app.put('/api/panel/products/:id', async (req, res) => {
app.post('/api/panel/products/images/alt/regenerate', async (_req, res) => {
app.get('/api/panel/security-settings', async (_req, res) => {
app.put('/api/panel/security-settings', async (req, res) => {
app.get('/api/panel/security-status', async (_req, res) => {
app.delete('/api/panel/products/:id', async (req, res) => {
app.get('/panel', (_req, res) => {
app.get(['/panel/security', '/panel/seguridad'], (_req, res) => {
